language: node_js

script: "/bin/date"

node_js:
  - 0.10

before_install:
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in deploy_key.enc -out deploy_key -d

install : npm install
script  : npm start

after_success:
  - chmod 600 deploy_key
  - mv deploy_key ~/.ssh/id_rsa
  - git config user.email "AlexeyAnshakov@users.noreply.github.com"
  - git config user.name "Alexey Anshakov"
  - git checkout master
  - node -e 'p=process;p.exit(p.argv[1]+p.argv[2]==="AlexeyAnshakov"?0:1)' `git log -1 --format='%an'` && npm version patch -m '%s[ci skip]';echo
  - git remote set-url origin git@github.com:webRunes/Plus-WRIO-App.git
  - git push origin master
  - rm ~/.ssh/id_rsa

deploy:
  provider: s3
  access_key_id:
    secure: U1SnSfzC8L+66H04IruqD6taOM+UZACCDHp7IaM4MkF7Y62ibv2e1QfLUg1eqsNuELKcpDdSQ5EUPcR8+RgVSVd4KhsUhL2eq3hL3QfUDWc9zfl8f6fQFeIiqhsaIcGPYg1/yQFIRDYyGpMaFMBEUWS4FQ810lOOLRzXcZlJV6Q=
  secret_access_key:
    secure: jS/GixCUB4isSx3Cn+EPlyYq4wP9XKfh4v7j0fZwe2QWFdwVlE8NH8DWuLQOrw6QfBa++qEg58o4mxe8uf446Au/NcKsHtykunfYGI9eV8iPvhFVHOW4SzvMcuwfVyoJPc4TyWawKqoff+bd/TVN5lqmUwtpKBS57reMHWxdD/A=
  bucket: wrioos.com
  upload-dir: Plus-WRIO-App
  acl: public_read
  
